apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-qgzdjl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-qgzdjl
    app.kubernetes.io/part-of: jvm-build-suite-application-kfys
  name: jvm-build-suite-component-qgzdjl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-qgzdjl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-qgzdjl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-foex-tenant/jvm-build-suite-application-kfys/jvm-build-suite-component-qgzdjl@sha256:7e64ac7a4c0da350a151db5249e5f081dc72f8190d20c0f4f3ea7da87f1ac825
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
